#端口号
server:
  port: 8090

#数据源
spring:
  #加密
  encrypt:
    key: AsukaThunder
    debug: true

  devtools:
    restart:
      enabled: false

  datasource:
    url: 'jdbc:mysql://localhost:3306/asuka_thunder?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8_bin&serverTimezone=Asia/Shanghai'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #JPA配置
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

  #模板配置
  thymeleaf:
    check-template-location: false
    check-template: false

